[package]
name = "montyhall6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = { version = "4.3.0", features = ["derive"] }
fraction = "0.13.1"
